### ISSUE TITLE
What's your favorite F# Feature? Least Favorite? 

### ISSUE THREAD

**Issue by Rickasaurus** [7sharp9/AMA#10]

**Comment by 7sharp9** [comment]
Thats a good question Rick.

Probably my favourite feature would be pattern matching as it is quite encompassing of the language, its a very complete feature.

My least favourite, that's a bit more tricky as there are quite a few niggles, probably most around incomplete features.  Explicit only interfaces are pretty annoying, as are events, I can never remember the correct semantics for invoking creating events.  Other annoyances include the incomplete quotations the fact they are lossy and are language incomplete and only really for quoting F# to other languages rather than bi-directional quoting and unquoting.  It's a shame as it would of been a killer feature. Records are annoying too, the fact they are missing constructor's relying on only inference for creation even though the constructor exists but its suppressed!
