### ISSUE TITLE
Why mono / OSX?

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [7sharp9/AMA#2]
You've made huge efforts and spent lot of time to promote xplat F# - working on all desktop platforms + major mobile ones. Why not just be happy with targeting Windows?

**Comment by 7sharp9** [comment]
When I first started F#, my first project was building a C10k _(10,000 concurrent clients)_ web server using F#.  I had solved similar problems using C# on Windows so I followed suit using a Windows VM running on an iMac.  

I think around 2009 I had bought an iMac to try out at home having got frustrated with using Windows at work all day I wanted something different at home, so I spend time using F# with Visual Studio on a Windows VM running on my mac.   

Months later it became frustrating to use the VM all the time, I wanted a more native Mac experience.  So I stated looking at the open source projects that allowed you to use F# on a mac with mono, most were derelict so I spent some time getting MonoDevelop working with the FSharpBinding project that had been bit rotting for a while.  

I think its important to give people choice, not everyone wants to use Windows, I was a Windows user from Windows 3.11 through to Windows Vista before I decided to try out using a Mac and found I preferred it.

**Comment by 7sharp9** [comment]
The x-platform side of things is mixed, part of it was its a challenge to get F# working in different areas, someone once said they didn't think F# would work on iOS because of generic limitations in the mono AOT compiler so I spent a few nights hacking to prove it could  :-)

Its important to use the right tool for the job, its also important to explore the boundaries too.
