### ISSUE TITLE
Tip/s to balance between tech and business for someone who is starting in tech consulting or tech industry

### ISSUE THREAD

**Issue by kunjee17** [7sharp9/AMA#9]
Love for tech and excitement for tech many times remove the balance between business and tech. 

Simple example from one of my earlier company that even though CTO loved and worked in F#. As company grows he shifted to Java for totally business reasons. Means not even Scala... 

So question is how to keep things interesting while keeping the business part going. Be it salary or consulting.

**Comment by 7sharp9** [comment]
I think the key thing is a desire to explore and experiment, this can keep things fresh and interesting.  You can also use this to explore the periphery of your technology, a word of warning though, you can often find the technology your were excited about has large limitations that are not actively advertised.   

You can also turn this on its head though and use this is a way to either contribute to that technology and fill the holes or find new areas in tech that fit this area.

Ive had to make decisions to abandon certain technologies and use others, Im not sure if it comes under business reason or logistical ones.  For one project I worked on there was a mobile app that was developed using F#, near the middle of the project I had to make a decision to completely abandon F# and Xamarin in favour of re-writing the whole thing with native Swift.  This was due to bigs in the Xamarin linker, that although patched quite quickly the fix was not going to be propagated to Microsoft Mobile Center for months which meant no CI build.  I should mention this was not the only bug in the Xamarin linker, simply the final straw in a series of issues.  Again you can turn this to your advantage by learning and exploring the realms of Swift for example and re-apply some interesting points you find back to other technologies you already know.

**Comment by 7sharp9** [comment]
@kunjee17 I hope that answers the question?

**Comment by kunjee17** [comment]
Thanks @7sharp9  👍
